apps/courses/urls.py
from django.conf.urls import url
from . import views

app_name = 'coures'

urlpatterns = [
    url(r'coures/$',views.CouresInfo ,name='couresinfo'),
    url(r'couresdetail/(\d+)/$',views.CouresDetail ,name='couresdetail'),
    url(r'couresvideo/(\d+)/$',views.CouresVideo ,name='couresvideo'),
    url(r'courescomment/$',views.CouresComment ,name='courescomment'),
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

pro/urls.py
from django.contrib import admin
from django.urls import path,include
import xadmin

urlpatterns = [
    # path(r'^admin/', admin.site.urls),
    path(r'xadmin/', xadmin.site.urls),
    path(r'captcha/', include('captcha.urls')),
    path(r'ueditor/', include('DjangoUeditor.urls')),
    path(r'users/', include('users.urls' ,namespace='users')),
    path(r'courses/', include('courses.urls',namespace='coures' )),
    path(r'orgs/', include('orgs.urls' ,namespace='orgs')),
    path(r'operations/', include('operations.urls',namespace='operations')),
]

'''设置全局的 400 500 错误页面'''
handler404 = 'users.views.error_404'
handler500 = 'users.views.error_500'

apps/courses/models.py
from django.db import models
from datetime import datetime
from orgs.models import *

# Create your models here.

class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/',max_length=200,verbose_name='课程封面')
    name = models.CharField(max_length=200,verbose_name='名称')
    study_time = models.IntegerField(default=0,verbose_name='学习时长')
    study_num = models.IntegerField(default=0,verbose_name='学习人数')
    level = models.CharField(choices=(('gj','高级'),('zj','中级'),('cj','初级')),verbose_name='课程难度',max_length=20)
    love_num = models.IntegerField(default=0,verbose_name='收藏数')
    click_num = models.IntegerField(default=0,verbose_name='访问量')
    desc = models.CharField(max_length=200,verbose_name='课程简介')
    detail = models.TextField(verbose_name='课程详情')
    category = models.CharField(max_length=200,choices=(('qd','前端'),('hd','后端')),verbose_name='课程类别')
    course_notice = models.CharField(max_length=200,verbose_name='课程公告')
    course_need = models.CharField(max_length=200,verbose_name='课程需知')
    teacher_tell = models.CharField(max_length=200,verbose_name='老师教导')
    # add_time = models.DateTimeField(default=datetime.now(),verbose_name='添加时间')
    orgsinfo = models.ForeignKey(OrgInfo,verbose_name='所属机构',on_delete=models.CASCADE)
    teacherinfo = models.ForeignKey(TeacherInfo,verbose_name='所属老师',on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '课程信息'
        verbose_name_plural = verbose_name

class LessonInfo(models.Model):
    name = models.CharField(max_length=200,verbose_name='章节名称')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    courseinfo = models.ForeignKey(CourseInfo,verbose_name='所属课程',on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '章节信息'
        verbose_name_plural = verbose_name

class VideoInfo(models.Model):
    name = models.CharField(max_length=200,verbose_name='视频名称')
    study_time = models.IntegerField(default=0,verbose_name='视频时长')
    url = models.URLField(default='#',verbose_name='视频链接')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    lessoninfo = models.ForeignKey(LessonInfo,verbose_name='所属章节',on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '视频信息'
        verbose_name_plural = verbose_name

class SourceInfo(models.Model):
    name = models.CharField(max_length=200,verbose_name='资源名称')
    down_load = models.FileField(upload_to='source/',verbose_name='文件下载',max_length=200)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    courseinfo = models.ForeignKey(CourseInfo,verbose_name='课程信息',on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '资源信息'
        verbose_name_plural = verbose_name














apps/operations/models.py
from django.db import models
from datetime import datetime
from users.models import *
from courses.models import *

class UserAsk(models.Model):
    name = models.CharField(max_length=30,verbose_name='姓名')
    phone = models.CharField(max_length=100,verbose_name='手机')
    course = models.CharField(max_length=30,verbose_name='课程名')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='咨询时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '咨询信息'
        verbose_name_plural = verbose_name


class UserLove(models.Model):
    love_man = models.ForeignKey(UserProfile,verbose_name='收藏用户',on_delete=models.CASCADE)
    love_id = models.IntegerField(verbose_name='收藏ID')
    love_type = models.IntegerField(choices=((1,'org'),(2,'course'),(3,'teacher')),verbose_name='收藏类别')
    love_status = models.BooleanField(default=False,verbose_name='收藏状态')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='收藏时间')

    def __str__(self):
        return self.love_man.username

    class Meta:
        verbose_name = '收藏信息'
        verbose_name_plural = verbose_name

class UserCourse(models.Model):
    study_man = models.ForeignKey(UserProfile,verbose_name='学习用户',on_delete=models.CASCADE)
    study_course = models.ForeignKey(CourseInfo,verbose_name='学习课程',on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now,verbose_name='学习时间')

    def __str__(self):
        return self.study_man.username
    class Meta:
        unique_together = ('study_man','study_course')
        #联合唯一 只能增加一次
        verbose_name = '用户学习课程信息'
        verbose_name_plural = verbose_name

class UserComment(models.Model):
    comment_man = models.ForeignKey(UserProfile,verbose_name='评论用户',on_delete=models.CASCADE)
    comment_course = models.ForeignKey(CourseInfo,verbose_name='评论课程',on_delete=models.CASCADE)
    comment_content = models.CharField(max_length=200,verbose_name='评论内容')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='学习时间')

    def __str__(self):
        return self.comment_content

    class Meta:
        verbose_name = '评论信息'
        verbose_name_plural = verbose_name

class UserMessage(models.Model):
    message_man = models.IntegerField(default=0,verbose_name='消息用户')
    message_content = models.CharField(max_length=200,verbose_name='消息内容')
    message_status = models.BooleanField(default=False,verbose_name='消息状态')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='学习时间')

    def __str__(self):
        return self.message_content

    class Meta:
        verbose_name = '消息信息'
        verbose_name_plural = verbose_name






templates/coures/coures.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>couresinfo</title>
</head>
<body>
    <div> this is couresinfo </div>
    <div>
        {% for couinfo in pages %}
        <p>{% if couinfo.level == 'cj' %}
            初级
            {% elif couinfo.level == 'zj' %}
            中级
            {% else %}
            高级
            {% endif %}
        </p>
        {% endfor %}
    </div>

    <div>
        <ul>
            <li ><a href="?sort=" {% if sort == '' %} style="color: red" {% endif %}>all</a></li>
            <li><a href="?sort=love_num" {% if sort == 'love_num' %} style="color: red" {% endif %}>lovenum</a></li>
            <li><a href="?sort=click_num" {% if sort == 'click_num' %} style="color: red" {% endif %}>clicknum</a></li>
        </ul>
    </div>
    {% for coures in pages %}
        <p><a href="{% url 'coures:couresdetail' coures.id %}">{{ coures.name }} -- click_num:{{ coures.click_num }} -- love_num:{{ coures.love_num }} -- {{ coures.level }}</a></p>
        {{ coures.id }}
    {% endfor %}


    <div class="pages">
        <ul>
            {% if pages.has_previous %}
            <li><a href="?pagenum={{ pages.previous_page_number }}&sort={{ sort }}">上一页</a></li>
            {% endif %}

            {% for num in pages.paginator.page_range %}
            <li><a href="?pagenum={{ num }}&sort={{ sort }}">{{ num }}</a></li>
            {% endfor %}

            {% if pages.has_next %}
            <li><a href="?pagenum={{ pages.next_page_number }}&sort={{ sort }}">下一页</a></li>
            {% endif %}
        </ul>
    </div>

</body>
</html>

templates/coures/couresdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>couresdetail</title>
</head>
<body>
    <div>this is couresdetail</div>

        <p>{{ couresdetail }} -- <a href="{% url 'coures:couresvideo' couresdetail.id %}"><img src="{{ MEDIA_URL }}{{ couresdetail.image }}"></a></p>

</body>
</html>

templates/coures/couresvideo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>video</title>
</head>
<body>
    <div>this is couresvideo html</div>
    <p>{{ couresinfo.name }}</p>

    {% for lesson in couresinfo.lessoninfo_set.all %}
        <p>{{ lesson }}</p>
        {% for video in lesson.videoinfo_set.all %}
            <p>{{ video.url }}</p>
        {% endfor %}
    {% endfor %}
    <button type="submit" name="jssc" id="jssc">收藏</button>
    {% for cou in couresinfo.usercourse_set.all|slice:':6' %} <!--显示多少条信息 -->
            <img src="{{ MEDIA_URL }}{{ cou.study_man.image }}">
    {% endfor %}

    <textarea name="pl" id="pl" ></textarea>
    <button type="submit" id="pingl">提交</button>
    <hr>
    {% for sort in sort_coures %}
        {{ forloop.counter }} -- {{ sort }}
    {% endfor %}

</body>
<script>


    $('#pingl').click(function () {
        var couresid = {{ couresinfo.id }};
        var content = $('#pl').val();
        $.ajax({
            type:'POST',
            url:'{% url 'coures:courescomment' %}',
            data:{
                couresid : couresid,
                content : content,
                csrfmiddlewaretoken:'{{ csrf_token }}',
            },
            success:function (callback) {
                if (callback.status == 'ok'){
                    window.location.reload()
                }else{
                    alert('error')
                }
            },
        })
    })
</script>
</html>