apps/courses/urls.py
from django.conf.urls import url
from . import views

app_name = 'coures'

urlpatterns = [
    url(r'coures/$',views.CouresInfo ,name='couresinfo'),
    url(r'couresdetail/(\d+)/$',views.CouresDetail ,name='couresdetail'),
    url(r'couresvideo/(\d+)/$',views.CouresVideo ,name='couresvideo'),
    url(r'courescomment/$',views.CouresComment ,name='courescomment'),
]

apps/operations/urls.py
from django.conf.urls import url
from . import views

app_name = 'operations'

urlpatterns = [
    url(r'user_ask/$',views.user_ask,name='user_ask'),
    url(r'user_love/$',views.user_love,name='user_love'),
    url(r'user_dellove/$',views.user_dellove,name='user_dellove'),
]

apps/orgs/urls.py
from django.conf.urls import url
from . import views

app_name = 'orgs'

urlpatterns = [
    url(r'orgs/$',views.OrgsList,name='orgs'),
    url(r'orgsdetail/(\d+)/$',views.OrgsDetail,name='orgsdetail'),

]

apps/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'users/$',views.Home,name='index'),
    url(r'usersclass/$',views.IndexHone.as_view(),name='indexcclass'),
    url(r'register/$',views.register,name='register'),
    url(r'login/$',views.userlogin,name='login'),
    url(r'users_active/(\w+)/$',views.users_active,name='users_active'),
    url(r'users_reset/(\w+)/$',views.users_reset,name='users_reset'),
    url(r'forgetpwd/$',views.forgetpwd,name='forgetpwd'),
    url(r'userinfo/$',views.UserInfo,name='userinfo'),
    url(r'userchangeimage/$',views.UserChangeImageForm,name='userchangeimage'),
    url(r'userchangeinfo/$',views.UserChangeInfo,name='userchangeinfo'),
    url(r'updateemail/$',views.UpdateEmail,name='updateemail'),
    url(r'emailcode/$',views.EmailCode,name='emailcode'),
    url(r'resetemail/$',views.ResetEmail,name='resetemail'),
    url(r'usercoures/$',views.UserCoures,name='usercoures'),
    url(r'userlove/$',views.UserLoveOrg,name='userlove'),
]




extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

pro/urls.py
from django.contrib import admin
from django.urls import path,include
import xadmin

urlpatterns = [
    # path(r'^admin/', admin.site.urls),
    path(r'xadmin/', xadmin.site.urls),
    path(r'captcha/', include('captcha.urls')),
    path(r'ueditor/', include('DjangoUeditor.urls')),
    path(r'users/', include('users.urls' ,namespace='users')),
    path(r'courses/', include('courses.urls',namespace='coures' )),
    path(r'orgs/', include('orgs.urls' ,namespace='orgs')),
    path(r'operations/', include('operations.urls',namespace='operations')),
]

'''设置全局的 400 500 错误页面'''
handler404 = 'users.views.error_404'
handler500 = 'users.views.error_500'

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime

# Create your models here.
class UserProfile(AbstractUser):
    # username = models.CharField(max_length=200,verbose_name='用户姓名')
    image = models.ImageField(upload_to='user/',max_length=200,verbose_name='头像',blank=True)
    nick_name = models.CharField(max_length=200,verbose_name='昵称',blank=True)
    birthday = models.DateTimeField(verbose_name='生日',blank=True,null=True)
    gender = models.CharField(verbose_name='性别',choices=(('girl','女'),('boy','男')),default='girl',max_length=20)
    tel = models.CharField(max_length=11,verbose_name='手机')
    address = models.CharField(max_length=100,verbose_name='地址',blank=True)
    email = models.EmailField()
    add_time = models.DateTimeField(default=datetime.now(),verbose_name='添加时间')
    is_start = models.BooleanField(default=False,verbose_name='是否激活')

    def __str__(self):
        return self.username

    def get_mes_count(self):
        from operations.models import UserMessage
        #获取未读消息的总数
        messagecount = UserMessage.objects.filter(message_man=self.id,message_status=False).count()
        return messagecount

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

class Banner(models.Model):
    image = models.ImageField(upload_to='banner/',verbose_name='广告图',max_length=200)
    url = models.URLField(default='https://www.baidu.com',verbose_name='链接',max_length=200)
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间',max_length=200)

    def __str__(self):
        return str(self.image)

    class Meta:
        verbose_name = '广告信息'
        verbose_name_plural = verbose_name

class EmailVerifyCode(models.Model):
    code = models.CharField(max_length=200,verbose_name='邮箱验证码')
    email = models.EmailField(verbose_name='验证邮箱')
    send_type = models.IntegerField(choices=((1,'register'),(2,'forget'),(3,'change')),verbose_name='验证码类型')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间', max_length=200)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = '邮箱验证'
        verbose_name_plural = verbose_name



apps/users/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import *

class UserRegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True,min_length=3,max_length=10,error_messages={
        'required':'你输入的不正确',
        'min_length':'必须超过三个字符',
        'max_length':'必须小于10个字符'
    })
    captcha = CaptchaField()


class UserLoginForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True,min_length=3,max_length=10,error_messages={
        'required':'你输入的不正确',
        'min_length':'必须超过三个字符',
        'max_length':'必须小于10个字符'
    })



class ForgetPwd(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField()


class UserResetForm(forms.Form):
    password = forms.CharField(required=True,min_length=3,max_length=10,error_messages={
        'required':'你输入的不正确',
        'min_length':'必须超过三个字符',
        'max_length':'必须小于10个字符'
    })
    password1 = forms.CharField(required=True,min_length=3,max_length=10,error_messages={
        'required':'你输入的不正确',
        'min_length':'必须超过三个字符',
        'max_length':'必须小于10个字符'
    })


class UserChangeImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields= ['image']

class UserChangeInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name','tel']

class UserChangeEmailForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['email']


class UserResetEmailForm(forms.ModelForm):
    class Meta:
        model = EmailVerifyCode
        fields = ['email','code']


apps/users/views.py
from django.shortcuts import render ,redirect ,reverse
from django.http import HttpResponse
from .models import *
from .forms import *
from django.db.models import Q
from django.contrib.auth import authenticate,login,logout
from tools.send_mail_tools import send_mail_code
from django.http import JsonResponse
from orgs.models import *
from operations.models import *
from django.views.generic import View

'''使用类方法完成视图'''
def error_404(request):
    return render(request,'error_404.html')

def error_500(request):
    return render(request,'error_500.html')

class IndexHone(View):
    def get(self,request):
        return render(request,'users/index.html')
    def post(self,request):
        return render(request,'users/index.html')


def Home(request):
    return render(request,'users/index.html')

def register(request):
    if request.method == 'GET':
        user_register_form = UserRegisterForm()
        return render(request, 'users/register.html',{
            'user_register_form':user_register_form
        })
    elif request.method == 'POST':
        user_register_form = UserRegisterForm(request.POST)
        if user_register_form.is_valid():
            email = user_register_form.cleaned_data['email']
            password = user_register_form.cleaned_data['password']
            userlist = UserProfile.objects.filter(Q(username = email)|Q(email = email))
            if userlist:
                return HttpResponse('success')
            else:
                a = UserProfile()
                a.username = email
                a.set_password(password)
                a.email = email
                send_mail_code(email,1)
                a.save()
                return redirect(reverse('users:index'))
        else:
            return render(request,'users/register.html',{
                'user_register_form':user_register_form
            })



def userlogin(request):
    if request.method == 'GET':
        return render(request,'users/login.html')
    else:
        user_login_forms = UserLoginForm(request.POST)
        if user_login_forms.is_valid():
            email = user_login_forms.cleaned_data['email']
            password = user_login_forms.cleaned_data['password']
            user = authenticate(username=email, password=password)
            if user.is_start:
                login(request.user)
                return redirect(reverse('users:index'))
            else:
                return HttpResponse('请到邮箱里激活账号')
        else:
            return render(request,'users/login.html',{
                'user_login_forms':user_login_forms
            })


def users_active(request,code):
    if code:
        email_ver_list = EmailVerifyCode.objects.filter(code = code)
        if email_ver_list:
            email_ver = email_ver_list[0]
            email = email_ver.email
            user_list = UserProfile.objects.filter(username=email)
            if user_list:
                user = user_list[0]
                user.is_start = True
                user.save()
                return redirect(reverse('users:index'))
            else:
                pass
        else:
            pass
    else:
        pass


def forgetpwd(request):
    if request.method == 'GET':
        forget_pwd = ForgetPwd()
        return render(request,'users/forgetpwd.html',{
            'forget_pwd':forget_pwd
        })
    else :
        user_forget_form = ForgetPwd(request.POST)
        if user_forget_form.is_valid():
            email = user_forget_form.cleaned_data['email']
            userlist = UserProfile.objects.filter(email=email)
            # print(userlist.values())  返回的是一个queryset 对象
            if userlist:
                user = userlist[0]
                email = user.email
                send_mail_code(email,2)
                return HttpResponse('please go email update password')
            else:
                return render(request,'users/forgetpwd.html',{
                    'msg':'user not in '
                })

        else:
            return render(request , 'users/forgetpwd.html',{
                'user_forget_form':user_forget_form
            })

def users_reset(request,code):
    if code:
        if request.method == 'GET':
            return render(request,'users/reset.html',{
                'code':code
            })
        else:
            user_reset_form = UserResetForm(request.POST)
            if user_reset_form.is_valid():
                password = user_reset_form.cleaned_data['password']
                password1 = user_reset_form.cleaned_data['password1']
                if password == password1:
                    email_ver_list = EmailVerifyCode.objects.filter(code = code)
                    if email_ver_list:
                        email_ver = email_ver_list[0]
                        email = email_ver.email
                        user_list = UserProfile.objects.filter(email = email)
                        if user_list:
                            user = user_list[0]
                            user.set_password(password)
                            user.save()
                            return redirect(reverse('users:login'))
                        else:
                            pass
                    else:
                        pass
                elif password != password1:
                    return render(request,'users/reset.html',{
                        'msg':'password error',
                        'code':code
                    })
                else:
                    pass

            else:
                return render(request, 'users/reset.html', {
                    'user_reset_form': user_reset_form,
                    'code': code
                })
    else:
        pass




def UserInfo(request):
    user = request.user
    print(user)
    return render(request,'users/userinfo.html')


def UserChangeImageForm(request):
    userchangeimageform = UserChangeImageForm(request.POST,request.FILES,instance=request.user) #instance 对当前用户做修改
    if userchangeimageform.is_valid():
        userchangeimageform.save(commit=True)
        return JsonResponse({
            'status':'ok'
        })
    else:
        return JsonResponse({
            'status':'fail'
        })



def UserChangeInfo(request):
    '''修改用户名与电话'''
    userchangeinfoforms = UserChangeInfoForm(request.POST,instance=request.user)
    if userchangeinfoforms.is_valid():
        userchangeinfoforms.save(commit=True)
        return JsonResponse({
            'status':'ok'
        })
    else:
        return JsonResponse({
            'status':'fail'
        })

def UpdateEmail(request):
    return render(request,'users/updateemail.html')

from datetime import datetime

def EmailCode(request):
    userchangeemail_form = UserChangeEmailForm(request.POST)
    if userchangeemail_form.is_valid():
        email = userchangeemail_form.cleaned_data['email']
        userlist = UserProfile.objects.filter(Q(email=email)|Q(username=email))
        if userlist:
            return JsonResponse({
                'status':'fail',
                'msg':'email exist'
            })
        else:
            '''
            查询邮箱验证码表中有没有发送过验证码 如果有就 60秒后再发送 如果没有就直接发送
            '''
            email_list_ever = EmailVerifyCode.objects.filter(email=email,send_type=3)
            if email_list_ever:
                '''获取当前最新的验证码信息'''
                email_list = email_list_ever.order_by('-add_time')[0]
                if (datetime.now()-email_list.add_time).seconds > 60:
                    '''删除之前的验证码'''
                    email_list_ever.delete()
                    send_mail_code(email,3)
                    return JsonResponse({
                        'status':'ok',
                        'msg':'email send code success'
                    })
                else:
                    return JsonResponse({
                        'status':'fail',
                        'msg':'time error'
                    })
            else:
                send_mail_code(email,3)
                return JsonResponse({
                        'status':'ok',
                        'msg':'email send code success'
                    })

    else:
        return JsonResponse({
            'status':'fail',
            'msg':'email not exist'
        })

def ResetEmail(request):
    resetemail_form = UserResetEmailForm(request.POST)
    if resetemail_form.is_valid():
        email = resetemail_form.cleaned_data['email']
        code = resetemail_form.cleaned_data['code']

        email_list_ver = EmailVerifyCode.objects.filter(email=email,code=code)
        if email_list_ver:
            email_list = email_list_ver[0]
            if (datetime.now() - email_list.add_time).seconds > 160 :
                return JsonResponse({
                    'status':'fail',
                    'msg':'timeout',
                })
            else :
                request.user.email = email
                request.user.username = email
                request.user.save()
                return JsonResponse({
                    'status':'ok',
                    'msg':'reset success'
                })
        else:
            pass

    else:
        pass


def UserCoures(request):
    usercoures = request.user.usercourse_set.all()
    coureslist = [coures.study_course  for coures in usercoures ]
    return render(request,'users/usercoures.html',{
        'coureslist':coureslist
    })


def UserLoveOrg(request):
    '''获取当前用户的收藏机构信息'''
    userloveorg_list = UserLove.objects.filter(love_man=request.user,love_type=1,love_status=True)
    userloveorgid = [ loveorg.love_id for loveorg in userloveorg_list ]


templates/users/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" href="{% static 'css/index.css' %}" rel="stylesheet">
    {% block title %}<title>base</title>{% endblock %}
</head>
<body>
    <header class="header">
        <div class="top">
            <p class="tel">TEL:15111111111</p>
            <p>{{ request.user.get_mes_count }}</p>
{#            {{ forloop.counter|divisibleby:'5' }} 被5整除的判断  #}
            <div class="login">
{#                {% if request.user.is_authenticate %}#}
                <a href="{% url 'users:register' %}">注册</a>
{#                <p> {{ request.user.usersname }}</p>#}
                <a href="{% url 'users:login' %}">登录</a>
                <a href="">个人中心</a>
{#                {% endif %}#}
            </div>
        </div>
        <div class="toplogo">
            <img src="{% static 'img/logo.jpg' %}" class="logo" />
            <input class="search" placeholder="search"> </input>
            <button type="button" class="searchbtu" id="jssearch">搜索</button>
{#            <span id="jssearch" class="jssrearchbtu" data-value="gkk">公开课</span>#}
{#            <ul id="jsselect" class="jsselect" >#}
{#                <li data-value="org">机构</li>#}
{#                <li data-value="teacher">老师</li>#}
{#                <li data-value="course">课程</li>#}
{#            </ul>#}
        </div>
        {% block menu %}<menu class="nav">
            <ul class="navlist">
                <li><a href="#">首页</a></li>
                <li><a href="{% url 'orgs:orgs' %}">机构</a></li>
                <li><a href="#">课堂</a></li>
                <li><a href="#">老师</a></li>
            </ul>
        </menu>{% endblock %}
    </header>

    {% block main %}

    {% endblock %}

    {% block footer %}<footer class="footer">
        <div class="footerInfo">tihs is footer</div>
        <img src="#">
    </footer>{% endblock %}
</body>
<script>
    $(function () {

        $('#jssearch').click(function () {
                var search_type = $('#jssearch').attr('data-value');
                var keyword = $('#jssearch').val();
                var url = '';


                if (search_type == 'org'){
                    url = '{% url 'orgs:orgs' %}'
                }else if(search_type == 'teacher'){
                    url = '{% url 'orgs:orgs' %}'
                }else{
                    url = '{% url 'coures:couresinfo' %}'
                }

                url = url+'?keyword='+keyword
                window.location.href = url

            })

        })

</script>

</html>

templates/users/forgetpwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>forgetpwd</title>
</head>
<body>
   <div>
        <div class="left"></div>
        <div class="right">
            <form action="/users/forgetpwd/" method="post">
                {% csrf_token %}
                <input type="text"  name="email" placeholder="username"/>
                <p class="captcha">{{ forget_pwd.captcha }}</p>
                {{ user_register_form.captcha }}
                <input type="submit" value="submit" />
            </form>
            <p>
                {{ msg }}
                {% for key , err in forget_pwd.errors.items %}
                    {{ err }}
                {% endfor %}
            </p>
        </div>
    </div>
</body>
<script>
    $(function () {
        $('.captcha').click(function () {
            window.location.reload()
        })
    })


</script>

</html>

templates/users/index.html
{% extends 'users/base.html' %}

{% block main %}
    <div class="main">this is main</div>
{% endblock %}





templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
     <div>
        <div class="left"></div>
        <div class="right">
            <form action="/users/login/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="text"  name="email"/>
                <input type="password"  name="password"/>
                <input type="submit" value="登录" />
            </form>
            <p>
                {{ msg }}
                {% for key , err in user_register_form.errors.items %}
                    {{ err }}
                {% endfor %}
            </p>
        </div>
    </div>
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
</head>
<body>
    <div>
        <div class="left"></div>
        <div class="right">
            <form action="/users/register/" method="post">
                {% csrf_token %}
                <input type="text"  name="email"/>
                <input type="password"  name="password"/>
                {{ user_register_form.captcha }}
                <input type="submit" value="submit" />
            </form>
            <p>
                {{ msg }}
                {% for key , err in user_register_form.errors.items %}
                    {{ err }}
                {% endfor %}
            </p>
        </div>
    </div>
</body>
</html>

templates/users/reset.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>reset</title>
</head>
<body>
      <div>
        <div class="left"></div>
        <div class="right">
            <form action="{% url 'users:users_reset' code %}" method="post">
                {% csrf_token %}
                <input type="password"  name="password" placeholder="password" />
                <input type="password"  name="password1" placeholder="reenter password"/>
                <input type="submit" value="submit" />
            </form>
            <p>
                {{ msg }}
                {% for key , err in user_reset_form.errors.items %}
                    {{ err }}
                {% endfor %}
            </p>
        </div>
    </div>
</body>
</html>

templates/users/updateemail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>updateemail</title>
</head>
<body>
    <form  action="{% url 'users:emailcode' %}" method="post">
        {% csrf_token %}
        <input type="email" name="email" id="upemail" placeholder="please enter you email"/>
        <input type="text" name="emailcode" id="emailcode" placeholder="obtain code"/>
        <input type="submit" name="sub" id="sub" value="获取验证码"/>
        <input type="submit" name="complete" id="complete" value="完成" />
    </form>

</body>

<script>

    $(function () {
        $('#sub').click(function () {
            var eamil = $('#email').val();
            $.ajax({
                type:'POST',
                url:'{% url 'users:emailcode' %}',
                data:{
                    eamil:eamil,
                    csrfmiddlewaretoken:'{{ csrf_token }}',
                },
                success:function (callback) {
                    if (callback.status == 'ok'){
                        alert('please you emayl recv code')
                    }
                }
            })
        });

        $('#complete').click(function () {
            var email = $('#email').val();
            var code = $('#emailcode').val();
            $.ajax({
                type:'POST',
                url:'{% url 'users:resetemail' %}',
                data:{
                    email:email,
                    code:code,
                    csrfmiddlewaretoken:'{{ csrf_token }}'
                },
                success:function (callback) {
                    if (callback.status == 'ok'){
                        alert(callback.msg)
                        window.location.href = '{% url 'users:login' %}'
                    }else{
                        alert(callback.msg)
                    }
                }
            })
        });
    })

</script>

</html>

templates/users/usercoures.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>usercoures</title>
</head>
<body>
    {% for coures in coureslist %}
        {{ coures.id }}--{{ coures }} -- {{ coures.orgsinfo.name }}
    {% endfor %}

    {% for org in orgs %}
        <p>{{ org.name }}</p>
        <button type="button" id="cancle" class="cancle" data-favid="{{ org.id }}">取消收藏</button>
    {% endfor %}

</body>
    <script>
        $(function () {
            $('.cancle').click(function () {
                var loveid = $(this).attr('data-favid');
                var lovetype = 1;
                {#获取当前的点击事件的对象#}
                {#var obj = $(this);#}
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_dellove' %}',
                    data:{
                            love_id:loveid,
                            love_type:lovetype,
                    },
                    success:function (callback) {
                        if (callback.status == 'ok'){
                            alert(callback.msg);
                            {#调用当前的点击事件对象 并移除对应的对象#}
                            {#obj.parents('#cancel').remove()#}
                        }else{
                            alert(callback.msg);
                        }
                    },
                })
            })
        })
    </script>

</html>

templates/users/userinfo.html
{% extends 'users/base.html' %}

{% block title %}<title>userinfo</title> {% endblock %}


{% block menu %} {% endblock %}

{% block main %}
<form action="{% url 'users:userchangeinfo' %}" method="post" style="float: left ;margin:120px 0px 0px 320px">
{% csrf_token %}
<input  type="text" name="nick_name" id="nick_name" value="{{ request.user.nick_name }}"/>
<input  type="text" name="tel" id="tel" value="{{ request.user.tel}}"/>
{#<img src="{{ MEDIA_URL }}{{ request.user.image }}" />#}
{#<input type="file" id="userchange" name="userchange" />#}
<input type="submit" name="jsbtu" id="jsbtu" />
</form>

{% endblock %}

<script>
    $(function () {
        $('#jsbtu').click(function () {
            var nick_name = $('#nick_name').val();
            var tel = $('#tel').val();
            $.ajax({
                type:'POST',
                url:'{% url 'users:userchangeinfo' %}',
                data:{
                    nick_name:nick_name,
                    tel:tel,
                    csrfmiddlewaretoken:'{{ csrf_token }}',
                },
                success:function (callback) {
                    if (callback.status == 'ok'){
                            callback.msg;
                            window.location.reload()
                    }else{
                        callback.msg;
                    }
                }
            })
        })
    })

</script>
